use BabyStore
go
--Them login
exec sp_addlogin tuongvi, tuongvi123, BabyStore
exec sp_addlogin congbang, congbang123, BabyStore
exec sp_addlogin conghau, conghau123, BabyStore
exec sp_addlogin dangminh, dangminh123, BabyStore
go

--Tao nhom quyen
exec sp_addrole QUANLY
go

GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CA TO QUANLY
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CHITIETHOADON TO QUANLY
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CUAHANG TO QUANLY
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.DANHMUCSANPHAM TO QUANLY
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GIAMGIA TO QUANLY
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.KHACHHANG TO QUANLY
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.KHO TO QUANLY
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.LOAITAIKHOAN TO QUANLY
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.NHACUNGCAP TO QUANLY
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.NHANVIEN TO QUANLY
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.NHAPHANG TO QUANLY
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SANPHAM TO QUANLY
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TAIKHOAN TO QUANLY
GRANT SELECT, UPDATE ON dbo.KHO TO QUANLY
GRANT SELECT, UPDATE ON dbo.VIEW_CHITIETHOADON TO QUANLY
GRANT SELECT, UPDATE ON dbo.VIEW_HOADON TO QUANLY
GRANT SELECT ON dbo.VIEWSANPHAM TO QUANLY
GRANT SELECT ON dbo.VIEW_DOANHSO TO QUANLY
go

GRANT EXECUTE ON pro_DangNhap TO QUANLY
GRANT EXECUTE ON pro_DangKy TO QUANLY
go

GRANT SELECT ON fn_XemSanPhamTrangKhachHang TO QUANLY
GRANT SELECT ON fn_LocSanPhamTheoDanhMuc TO QUANLY
GRANT SELECT ON fn_TimKiemSanPham TO QUANLY
go

GRANT EXECUTE ON pro_DangKy TO QUANLY
GRANT SELECT ON Check_KH TO QUANLY
GRANT EXECUTE ON ReSL TO QUANLY
GRANT EXECUTE ON InSL TO QUANLY
GRANT EXECUTE ON Search_SP TO QUANLY
GRANT EXECUTE ON Insert_HD TO QUANLY
GRANT EXECUTE ON Insert_GG TO QUANLY
GRANT EXECUTE ON Update_GG TO QUANLY
GRANT EXECUTE ON ChiTietHD TO QUANLY
GRANT EXECUTE ON ListChiTietHD TO QUANLY
GRANT EXECUTE ON Delete_HD TO QUANLY
GRANT EXECUTE ON HienHDTheoIdHD TO QUANLY
go

GRANT EXECUTE ON HienAllHD TO QUANLY
GRANT EXECUTE ON DoanhSo TO QUANLY
GRANT EXECUTE ON HienHDTheoTG TO QUANLY
GRANT EXECUTE ON DoanhSoTheoTG TO QUANLY
GRANT EXECUTE ON ListHDTheoCH TO QUANLY
GRANT EXECUTE ON DoanhSoTheoCH TO QUANLY
GRANT EXECUTE ON ListHDTheoCHTG TO QUANLY
GRANT EXECUTE ON DoanhSoCHTG TO QUANLY
GRANT SELECT ON func_show_CH TO QUANLY
GRANT EXECUTE ON proc_ShowCH TO QUANLY
GRANT EXECUTE ON func_Check_Info TO QUANLY
GRANT EXECUTE ON proc_Check_Info TO QUANLY
GRANT EXECUTE ON Update_IDCH_for_Emp TO QUANLY
GRANT EXECUTE ON proc_Add_CH TO QUANLY
GRANT EXECUTE ON proc_UpdateCH TO QUANLY
GRANT SELECT ON func_show_CH_str TO QUANLY
GRANT EXECUTE ON proc_showCH_str TO QUANLY
GRANT SELECT ON func_show_acc TO QUANLY
GRANT EXECUTE ON proc_show_acC TO QUANLY
GRANT SELECT ON func_show_acc_str TO QUANLY
GRANT EXECUTE ON proc_show_acc_str TO QUANLY
GRANT EXECUTE ON proc_add_account TO QUANLY
GRANT EXECUTE ON proc_del_account TO QUANLY
GRANT EXECUTE ON proc_update_account TO QUANLY
GRANT EXECUTE ON show_list_cus TO QUANLY
GRANT SELECT ON func_show_cus_str TO QUANLY
GRANT EXECUTE ON show_list_cus_str TO QUANLY
GRANT EXECUTE ON add_customer TO QUANLY
GRANT EXECUTE ON del_customer TO QUANLY
GRANT EXECUTE ON update_customer TO QUANLY
GRANT EXECUTE ON proc_HienThiCa_Lam TO QUANLY
GRANT EXECUTE ON proc_ThemCA TO QUANLY
GRANT EXECUTE ON proc_Suaca TO QUANLY
GRANT EXECUTE ON proc_Xoa TO QUANLY
GRANT EXECUTE ON proc_ThemCH TO QUANLY
GRANT EXECUTE ON proc_HienThiCH TO QUANLY
GRANT EXECUTE ON proc_SuaCH TO QUANLY
GRANT SELECT ON func_HienDMSP TO QUANLY
GRANT EXECUTE ON proc_ThemDMSP TO QUANLY
GRANT EXECUTE ON proc_SuaDMSP TO QUANLY
GRANT EXECUTE ON Xoa_DMSP TO QUANLY
GRANT EXECUTE ON Hienthi_NCC TO QUANLY
GRANT EXECUTE ON Them_NCC TO QUANLY
GRANT EXECUTE ON Sua_NCC TO QUANLY
GRANT EXECUTE ON Xoa_NCC TO QUANLY
GRANT EXECUTE ON Tk_Ten_NCC TO QUANLY
GRANT EXECUTE ON pro_HienthiNV1 TO QUANLY
GRANT EXECUTE ON proc_HienthiIdCa TO QUANLY
GRANT EXECUTE ON proc_ThemNV TO QUANLY
GRANT EXECUTE ON proc_SuaNV TO QUANLY
GRANT EXECUTE ON proc_Timkiemtheodieukien TO QUANLY
GRANT EXECUTE ON pro_HienthiSP TO QUANLY
GRANT EXECUTE ON proc_ThemSP TO QUANLY
GRANT EXECUTE ON SuaSP TO QUANLY
GRANT SELECT ON fuc_SP_hethan TO QUANLY
GRANT EXECUTE ON SP_hethan TO QUANLY
GRANT EXECUTE ON proc_HienthiTK TO QUANLY
GRANT EXECUTE ON proc_Hienthi_loaitaikhoan TO QUANLY
GRANT EXECUTE ON proc_ThemTK TO QUANLY
GRANT EXECUTE ON proc_SưaTK TO QUANLY
GRANT EXECUTE ON proc_xoaTK TO QUANLY
GRANT EXECUTE ON tk_tk TO QUANLY
GRANT EXECUTE ON TK_TenDMSP TO QUANLY
go








exec sp_addrole NHANVIEN
go
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CHITIETHOADON TO NHANVIEN
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GIAMGIA TO NHANVIEN
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.KHACHHANG TO NHANVIEN
GRANT SELECT, UPDATE ON dbo.KHO TO NHANVIEN
GRANT SELECT, UPDATE ON dbo.VIEW_CHITIETHOADON TO NHANVIEN
GRANT SELECT, UPDATE ON dbo.VIEW_HOADON TO NHANVIEN
GRANT SELECT ON dbo.VIEWSANPHAM TO NHANVIEN
GRANT SELECT ON dbo.KHO TO NHANVIEN
GRANT SELECT ON dbo.NHACUNGCAP TO NHANVIEN
GRANT SELECT ON dbo.SANPHAM TO NHANVIEN
GRANT SELECT ON dbo.TAIKHOAN TO NHANVIEN
go
GRANT EXECUTE ON pro_DangKy TO NHANVIEN
GRANT SELECT ON Check_KH TO NHANVIEN
GRANT EXECUTE ON ReSL TO NHANVIEN
GRANT EXECUTE ON InSL TO NHANVIEN
GRANT EXECUTE ON Search_SP TO NHANVIEN
GRANT EXECUTE ON Insert_HD TO NHANVIEN
GRANT EXECUTE ON Insert_GG TO NHANVIEN
GRANT EXECUTE ON Update_GG TO NHANVIEN
GRANT EXECUTE ON ChiTietHD TO NHANVIEN
GRANT EXECUTE ON ListChiTietHD TO NHANVIEN
GRANT EXECUTE ON Delete_HD TO NHANVIEN
GRANT EXECUTE ON HienHDTheoIdHD TO NHANVIEN
go










--Them user
exec sp_adduser tuongvi, tuongvi, QUANLY
exec sp_adduser congbang, congbang, QUANLY
exec sp_adduser conghau, conghau, NHANVIEN
exec sp_adduser dangminh, dangminh, NHANVIEN

